265293 - Create changelog entries
nanego/my-dcim pull request #103
Opened 2023-10-25 14:23 UTC by nicolas-brousse

2023-11-08 14:40 UTC, B-Rass approved these changes

2023-11-08 14:47 UTC, B-Rass requested changes

2023-11-08 14:47 UTC, B-Rass commented on app/views/changelog_entries/index.html.erb
> +          <td><%= link_to "More details", changelog_entry_path(changelog_entry) %></td>
Utiliser du FR ou mieux mettre ça dans un fichier de trad

2023-11-08 14:47 UTC, B-Rass commented on app/views/changelog_entries/index.html.erb
> +          <td><%= link_to "More details", changelog_entry_path(changelog_entry) %></td>
En général sur cette vue d'ailleurs

2023-11-08 17:39 UTC, nicolas-brousse commented on app/views/changelog_entries/index.html.erb
> +          <td><%= link_to "More details", changelog_entry_path(changelog_entry) %></td>
J'ai fait une repasse

2023-11-10 12:36 UTC, B-Rass approved these changes
Good

2023-11-22 16:37 UTC, B-Rass approved these changes
Juste un check mais sinon c'est bon pour moi

2023-11-22 16:37 UTC, B-Rass commented on lib/tasks/convert_activities_to_changelog_entries.rake
Les commentaires laissés ici c'est voulu ?

2023-11-22 16:42 UTC, nicolas-brousse commented on lib/tasks/convert_activities_to_changelog_entries.rake
yes it is

2024-01-10 15:39 UTC, B-Rass commented
@nicolas-brousse y a des conflits FYI

2024-01-10 16:44 UTC, nicolas-brousse commented
> @nicolas-brousse y a des conflits FYI

Fixed

2024-01-17 10:32 UTC, merged