275817 - Settings consistency - Index
nanego/my-dcim pull request #104
Opened 2023-11-02 13:09 UTC by MBausson

2023-11-08 14:21 UTC, B-Rass requested changes
@MBausson Des petites optim' à faire et c'est good

2023-11-08 14:21 UTC, B-Rass commented on app/views/frames/index.html.erb
> +              <%= link_to 'Modifier', edit_frame_path(frame), class: 'btn btn-primary' %>
Ajouter autour des deux boutons une `div`

```html
<div class="btn-group btn-group-sm btn-group-vertical" role="group" aria-label="...">
```

2023-11-08 14:21 UTC, B-Rass commented on app/views/memory_types/index.html.erb
> +          Nouveau type de mémoire
```suggestion
          Nouveau type de RAM
```

2023-11-08 14:21 UTC, B-Rass commented on app/views/memory_types/index.html.erb
> +        <h1>Listing memory types</h1>
```suggestion
        <h1>Listing types de RAM</h1>
```

2023-11-08 14:21 UTC, B-Rass commented on app/views/memory_types/index.html.erb
> +                <%= link_to 'Supprimer', memory_type, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
@nicolas-brousse pas de trad' ici ?

2023-11-08 14:21 UTC, B-Rass commented on app/views/servers/index.html.erb
> +                <%= link_to 'Modifier', edit_server_path(server), class: 'btn btn-primary' %>
Ajouter autour des deux boutons une `div`

```html
<div class="btn-group btn-group-sm btn-group-vertical" role="group" aria-label="...">
```

2023-11-09 14:41 UTC, MBausson commented on app/views/servers/index.html.erb
> +                <%= link_to 'Modifier', edit_server_path(server), class: 'btn btn-primary' %>
@B-Rass J'ajoute cette div seulement sur ces 2 vues ? Ou sur toutes les index ?

2023-11-10 12:49 UTC, B-Rass commented on app/views/servers/index.html.erb
> +                <%= link_to 'Modifier', edit_server_path(server), class: 'btn btn-primary' %>
Oui c'était ça seulement sur ces deux vues

2023-11-10 12:50 UTC, B-Rass approved these changes
OK

2023-11-10 12:52 UTC, merged