275817 - i18n - Use i18n for Modele resource
nanego/my-dcim pull request #109
Opened 2023-11-10 13:12 UTC by MBausson

2023-11-22 16:50 UTC, nicolas-brousse requested changes
@MBausson you forgot to move string for controller flash messages

2023-11-22 16:50 UTC, nicolas-brousse commented on app/views/modeles/_enclosure_fields.html.erb
> +          <%= f.label t(".display") %>
```suggestion
          <%= f.label :display %>
```

To be manage in with ActiveRecord i18n translations

2023-11-22 16:50 UTC, nicolas-brousse commented on app/views/modeles/edit.html.erb
> +  t("breadcrumb.settings") => modeles_url,
```suggestion
  t("inventories") => modeles_url,
```

2023-11-22 16:50 UTC, nicolas-brousse commented on app/views/modeles/index.html.erb
> +  t("breadcrumb.settings") => modeles_url,
```suggestion
  t("inventories") => modeles_url,
```

2023-11-22 16:50 UTC, nicolas-brousse commented on app/views/modeles/index.html.erb
> +                  <%= t(".display") %>
```suggestion
                  <%= Enclosure.human_attribute_name(:display) %>
```

2023-11-22 16:50 UTC, nicolas-brousse commented on app/views/modeles/new.html.erb
> +  t("breadcrumb.settings") => modeles_url,
```suggestion
  t("inventories") => modeles_url,
```

2023-11-22 16:50 UTC, nicolas-brousse commented on app/views/pages/_params_menu.html.erb
> +    <a href="<%= frames_path %>" class="list-group-item <%= controller.controller_name == "frames" ? "active" : "" %>"><%= Frame.model_name.human %></a>
@MBausson for which issue this has been removed?

2023-11-22 16:50 UTC, nicolas-brousse commented on app/views/modeles/_form.html.erb
> +    <%= f.label :category, class: "col-sm-2 col-md-1 control-label" %>
```suggestion
    <%= f.label :category_id, class: "col-sm-2 col-md-1 control-label" %>
```

2023-11-22 16:50 UTC, nicolas-brousse commented on app/views/modeles/_form.html.erb
> +    <%= f.label :architecture, class: "col-sm-2 col-md-1 control-label" %>
```suggestion
    <%= f.label :architecture_id, class: "col-sm-2 col-md-1 control-label" %>
```

2023-11-22 16:50 UTC, nicolas-brousse commented on app/views/modeles/_form.html.erb
> +    <%= f.label :manufacturer, class: "col-sm-2 col-md-1 control-label" %>
```suggestion
    <%= f.label :manufacturer_id, class: "col-sm-2 col-md-1 control-label" %>
```

2023-11-22 16:50 UTC, nicolas-brousse commented on app/views/modeles/_form.html.erb
> +    <%= content_tag :span, Modele.human_attribute_name(:enclosures), class: "col-sm-2 control-label" %>
```suggestion
    <%= content_tag :span, Enclosure.model_name.human.pluralize, class: "col-sm-2 control-label" %>
```

2023-11-22 16:50 UTC, nicolas-brousse commented on app/views/modeles/_enclosure_fields.html.erb
> +          <%= f.label t(".grid_areas") %>
```suggestion
          <%= f.label :grid_areas %>
```

To be manage in with ActiveRecord i18n translations

2023-12-06 15:46 UTC, nicolas-brousse requested changes

2023-12-06 15:46 UTC, nicolas-brousse commented on app/views/modeles/_composant_fields.html.erb
> +      <%= f.text_field :name, { class: 'form-control', placeholder: t(".name") } %>
@MBausson Use existing rails way

in `activerecord.fr.yml`

```
  helpers:
    placeholder:
      modele:
        name: 'Nom'
```

And in this file
```suggestion
      <%= f.text_field :name, { class: 'form-control', placeholder: true } %>
```

2023-12-06 15:46 UTC, nicolas-brousse commented on config/locales/activerecord.fr.yml
> +        enclosures: Composants
@MBausson is this still used?

2023-12-06 15:46 UTC, nicolas-brousse commented on config/locales/fr.yml
> +      name: Nom
@MBausson is this still used?

2023-12-06 15:46 UTC, nicolas-brousse commented on config/locales/fr.yml
> +      display: Disposition
@MBausson is this still used?

2023-12-06 16:14 UTC, MBausson commented on app/views/modeles/_composant_fields.html.erb
> +      <%= f.text_field :name, { class: 'form-control', placeholder: t(".name") } %>
I can't achieve to translate the placeholder using this way, the placeholder stays in english ..

2023-12-06 16:24 UTC, MBausson commented on config/locales/activerecord.fr.yml
> +        enclosures: Composants
Yes

2023-12-06 16:25 UTC, MBausson commented on config/locales/fr.yml
> +      display: Disposition
display is no longer used

2023-12-06 16:49 UTC, nicolas-brousse commented on config/locales/activerecord.fr.yml
> +        enclosures: Composants
Why not using `Enclosure.model_name.human`?

2023-12-13 17:43 UTC, merged