275817 - i18n - Use i18n for category resource
nanego/my-dcim pull request #111
Opened 2023-11-10 15:04 UTC by MBausson

2023-11-22 16:41 UTC, nicolas-brousse requested changes
@MBausson you forgot to move string for controller flash messages

2023-11-22 16:41 UTC, nicolas-brousse commented on app/views/categories/edit.html.erb
> +    t("breadcrumb.settings") => modeles_url,
```suggestion
    t("inventories") => modeles_url,
```

2023-11-22 16:41 UTC, nicolas-brousse commented on app/views/categories/index.html.erb
> +  t("breadcrumb.settings") => modeles_url,
```suggestion
  t("inventories") => modeles_url,
```

2023-11-22 16:41 UTC, nicolas-brousse commented on app/views/categories/index.html.erb
> +              <%= t(".usage") %>
```suggestion
              <%= Category.human_attribute_name(:modeles_count) %>
```

2023-11-22 16:41 UTC, nicolas-brousse commented on app/views/categories/new.html.erb
> +  t("breadcrumb.settings") => modeles_url,
```suggestion
  t("inventories") => modeles_url,
```

2023-11-29 09:53 UTC, B-Rass requested changes
@MBausson on nous a demandé de traduire `Category` par `Catégorie` plutôt que `type de matériel`. J'ai fait les changements. Pense à checker qu'il ne reste pas d'autres changements à faire

2023-11-29 09:53 UTC, B-Rass commented on config/locales/fr.yml
> +      new_category: Ajouter un type de matériel
```suggestion
      new_category: Ajouter une catégorie
```

2023-11-29 09:53 UTC, B-Rass commented on config/locales/fr.yml
> +      title: Types de matériel
```suggestion
      title: Catégories
```

2023-11-29 09:53 UTC, B-Rass commented on config/locales/fr.yml
> +      delete_confirmation: Ce type de matériel ne pourra pas être supprimé tant qu'il aura au moins un modèle associé. Voulez-vous continuer ?
```suggestion
      delete_confirmation: Cette catégorie ne pourra pas être supprimée tant qu'elle aura au moins un modèle associé. Voulez-vous continuer ?
```

2023-12-06 11:12 UTC, nicolas-brousse commented on config/locales/activerecord.fr.yml
> +      category: Catégorie
@B-Rass `Catégorie` vs `Type de matériel`.

Was `Type de matériel` in breadcrumb

2023-12-06 13:52 UTC, B-Rass commented on config/locales/activerecord.fr.yml
> +      category: Catégorie
`Catégorie`

2023-12-06 14:00 UTC, nicolas-brousse approved these changes

2023-12-06 14:04 UTC, merged