Add endpoints for cable, port and connection
nanego/my-dcim pull request #113
Opened 2023-11-15 17:25 UTC by B-Rass

2023-11-22 15:56 UTC, B-Rass commented
@nicolas-brousse à review

2023-11-22 16:08 UTC, nicolas-brousse requested changes

2023-11-22 16:08 UTC, nicolas-brousse commented on app/controllers/ports_controller.rb
> -    end
Why this has been removed?

2023-11-29 10:34 UTC, nicolas-brousse approved these changes

2023-11-29 10:34 UTC, merged