Update params menu
nanego/my-dcim pull request #115
Opened 2023-11-29 11:21 UTC by B-Rass

2023-12-06 13:33 UTC, nicolas-brousse requested changes

2023-12-06 13:33 UTC, nicolas-brousse commented on app/views/contract_types/edit.html.erb
> +  ContractType.model_name.human(count: 2) => contract_types_path,
@B-Rass why `(count: 2)` over `pluralize`?

2023-12-06 13:33 UTC, nicolas-brousse commented on app/views/layouts/_inventories_dropdown.html.erb
> +    <li class="dropdown-header"><%= t("pages.params_menu.features.title")%></li>
```suggestion
    <li class="dropdown-header"><%= t("inventories_menu.features.title")%></li>
```

@B-Rass suggestion

2023-12-06 16:07 UTC, B-Rass commented on app/views/contract_types/edit.html.erb
> +  ContractType.model_name.human(count: 2) => contract_types_path,
pluralize -> `Type de contrats`
count: 2 -> `Types de contrat`

2023-12-13 16:24 UTC, nicolas-brousse approved these changes

2023-12-13 16:24 UTC, nicolas-brousse commented
@B-Rass two conflicts to resolve, otherwise LGTM

2023-12-20 14:27 UTC, merged