287580 - Datatable sort
nanego/my-dcim pull request #129
Opened 2024-01-24 10:54 UTC by MBausson

2024-01-24 15:54 UTC, B-Rass commented
@MBausson can you look after the conflicts? Thx!

2024-01-31 11:16 UTC, nicolas-brousse requested changes

2024-01-31 11:16 UTC, nicolas-brousse commented on app/controllers/modeles_controller.rb
> +    @types = sorted @modeles.group_by { |m| m.category.name }.sort_by { |categorie, modeles| categorie.to_s }
Doesn't work on this index. `sorted` is not on the right place.

2024-01-31 11:16 UTC, nicolas-brousse commented on app/views/architectures/index.html.erb
> +          <%= link_to pluralize(architecture.modeles.count, 'modèle', 'modèles'), modeles_path %>
Use i18n here. `Modele.model_name.human.pluralize(count: architecture.modeles.count)`.

2024-01-31 11:16 UTC, nicolas-brousse commented on app/views/sites/index.html.erb
> +        <% table.with_column(Site.human_attribute_name(:position)) do |site| %>
```suggestion
        <% table.with_column(Site.human_attribute_name(:position), sort_by: :position) do |site| %>
```

2024-01-31 11:16 UTC, nicolas-brousse commented on app/views/servers/index.html.erb
> +          <div class="btn-group btn-group-sm btn-group-vertical" role="group" aria-label="...">
Div to be removed. Let do the same as other tables. We will do some more changes later if necessary.

2024-01-31 11:16 UTC, nicolas-brousse commented on app/views/rooms/index.html.erb
> +                      data: { confirm: 'Cette salle ne pourra pas être supprimée tant qu\'elle sera associée à au moins un ilôt. Voulez-vous continuer ?' },
Move to i18n

2024-01-31 11:16 UTC, nicolas-brousse commented on app/views/rooms/index.html.erb
> +        <% table.with_column("Afficher sur la page d'accueil", sort_by: :display_on_home_page) do |room| %>
Move to i18n

2024-01-31 11:16 UTC, nicolas-brousse commented on app/views/rooms/index.html.erb
> +          <%= pluralize room.frames.count, 'chassis' %>
Move to i18n

2024-01-31 11:16 UTC, nicolas-brousse commented on app/views/rooms/index.html.erb
> +          <%= pluralize room.islets.count, 'îlot', 'îlots' %>
Move to i18n

2024-01-31 11:16 UTC, nicolas-brousse commented on app/views/rooms/index.html.erb
> +        <% table.with_column("Nom", sort_by: :name) do |room| %>
Move to i18n

2024-01-31 11:16 UTC, nicolas-brousse commented on app/views/rooms/index.html.erb
> +        <% table.with_column("Position", sort_by: :position) do |room| %>
Move to i18n

2024-01-31 11:16 UTC, nicolas-brousse commented on app/views/rooms/index.html.erb
> +        <% table.with_column("Contenu") do |room| %>
Move to i18n

2024-01-31 11:16 UTC, nicolas-brousse commented on app/views/rooms/index.html.erb
> +        <% table.with_column("Site") do |room| %>
Move to i18n

2024-01-31 11:23 UTC, nicolas-brousse requested changes

2024-01-31 11:23 UTC, nicolas-brousse commented on app/views/categories/index.html.erb
> +          </b>
Is it for a particular reason that you put a `<b>` tag around?

2024-01-31 11:23 UTC, nicolas-brousse commented on app/views/categories/index.html.erb
> +          <%= link_to "#{pluralize(category.modeles.count, 'modèle', 'modèles')}", modeles_path %>
Use i18n.

2024-01-31 11:23 UTC, nicolas-brousse commented on app/views/contract_types/index.html.erb
> +                      data: { confirm: 'Toutes les données concernant ce type de contrat seront supprimées, ainsi que les contrats de maintenance associés. Voulez-vous continuer ?' },
Moe in i18n.

2024-01-31 11:23 UTC, nicolas-brousse commented on app/views/disk_types/index.html.erb
> +          </b>
Is it for a particular reason that you put a `<b>` tag around?

2024-01-31 11:23 UTC, nicolas-brousse commented on app/views/domaines/index.html.erb
> +          </b>
Is it for a particular reason that you put a <b> tag around?

2024-01-31 11:23 UTC, nicolas-brousse commented on app/views/islets/index.html.erb
> +          </b>
Is it for a particular reason that you put a <b> tag around?

2024-01-31 11:23 UTC, nicolas-brousse commented on app/views/maintainers/index.html.erb
> +
```suggestion
```

Remove empty line

2024-01-31 13:01 UTC, MBausson commented on app/views/categories/index.html.erb
> +          </b>
I think I've seen it somewhere else before, I added it here so it is consistent

2024-01-31 13:32 UTC, nicolas-brousse requested changes

2024-01-31 13:32 UTC, nicolas-brousse commented on app/controllers/modeles_controller.rb
> +    @types = sorted(@modeles).group_by { |m| m.category.name }.sort_by { |categorie, modeles| categorie.to_s }
Prefer to call sorted on line 9 than here

2024-01-31 13:52 UTC, B-Rass requested changes
3 cleans sur les clés de trad'

si on mets pas la clé `zero` alors ça va afficher `1 xxxx`, même si le `count` = 0

2024-01-31 13:52 UTC, B-Rass commented on config/locales/activerecord.fr.yml
> +          one: 1 îlot
```suggestion
         zero: 0 îlot
          one: 1 îlot
```

2024-01-31 13:52 UTC, B-Rass commented on config/locales/activerecord.fr.yml
> +          one: 1 châssis
```suggestion
          zero: 0 châssis
          one: 1 châssis
```

2024-01-31 13:52 UTC, B-Rass commented on config/locales/activerecord.fr.yml
> +          one: 1 modèle
```suggestion
          zero: 0 modèle
          one: 1 modèle
```

2024-01-31 15:25 UTC, nicolas-brousse commented on app/views/islets/index.html.erb
> +          </b>
@MBausson ?

2024-01-31 15:26 UTC, nicolas-brousse commented on app/views/categories/index.html.erb
> +          </b>
Ok for me. But in this case make sure to add it on every table. It seems it is not always present.

2024-02-07 09:58 UTC, nicolas-brousse approved these changes

2024-02-07 10:03 UTC, B-Rass requested changes

2024-02-07 10:03 UTC, B-Rass commented on app/views/architectures/index.html.erb
> +          <%= link_to 'Modifier', edit_architecture_path(architecture), class: 'btn btn-primary' %>
Use traduction key here

2024-02-07 10:03 UTC, B-Rass commented on app/views/architectures/index.html.erb
> +          <%= link_to 'Supprimer',
Use traduction key here

2024-02-07 10:06 UTC, B-Rass requested changes

2024-02-07 10:06 UTC, B-Rass commented on app/controllers/disk_types_controller.rb
> +    @disk_types = DiskType.order(unit: :desc, quantity: :desc)
```suggestion
    @disk_types = DiskType.order(unit: :asc, quantity: :asc)
```

2024-02-07 10:11 UTC, nicolas-brousse commented on app/controllers/disk_types_controller.rb
> +    @disk_types = DiskType.order(unit: :desc, quantity: :desc)
Done

2024-02-07 10:11 UTC, nicolas-brousse commented on app/views/architectures/index.html.erb
> +          <%= link_to 'Supprimer',
Done

2024-02-07 10:11 UTC, nicolas-brousse commented on app/views/architectures/index.html.erb
> +          <%= link_to 'Modifier', edit_architecture_path(architecture), class: 'btn btn-primary' %>
Done

2024-02-07 10:13 UTC, B-Rass approved these changes

2024-02-07 10:15 UTC, merged