Use datatable in users index
nanego/my-dcim pull request #157
Opened 2024-03-20 16:09 UTC by nicolas-brousse

2024-03-20 16:27 UTC, B-Rass requested changes
My bad about the asc / desc changes

2024-03-20 16:27 UTC, B-Rass commented on app/components/list/data_table_component.rb
> +                   when :desc then { column: attribute, direction: :asc }
```suggestion
                   when nil then { column: attribute, direction: :asc }
                   when :asc then { column: attribute, direction: :desc }
```

2024-03-20 16:27 UTC, B-Rass commented on app/components/list/data_table_component.rb
> +                   when :desc then { column: attribute, direction: :asc }
In fact, keep it like it was, it should order a to z first.

2024-03-27 13:48 UTC, nicolas-brousse commented on app/components/list/data_table_component.rb
> +                   when :desc then { column: attribute, direction: :asc }
@B-Rass I changed it back

2024-03-27 14:53 UTC, B-Rass approved these changes

2024-03-27 14:53 UTC, merged