Add User suspension
nanego/my-dcim pull request #162
Opened 2024-03-27 14:51 UTC by nicolas-brousse

Requires https://github.com/nanego/my-dcim/pull/157 to be merged first.

2024-03-27 15:16 UTC, B-Rass requested changes

2024-03-27 15:16 UTC, B-Rass commented on app/controllers/users_controller.rb
> +      redirect_to users_path, alert: t(".flashes.can_be_updated")
```suggestion
      redirect_to users_path, alert: t(".flashes.cant_be_updated")
```

2024-03-27 15:16 UTC, B-Rass commented on config/locales/fr.yml
> +      can_be_updated: Une erreur est survenue pendant la mise à jour
```suggestion
      cant_be_updated: Une erreur est survenue pendant la mise à jour
```

2024-03-27 15:16 UTC, B-Rass commented on spec/requests/users_request_spec.rb
Don't we want to add all missing tests here ?

2024-03-27 15:19 UTC, B-Rass commented
Review done @nicolas-brousse

2024-03-27 15:20 UTC, B-Rass requested changes

2024-03-27 15:20 UTC, B-Rass commented on app/views/users/index.html.erb
> +              <%= link_to t("action.unsuspend"), unsuspend_user_path(user), data: { confirm: t("action.confirm") }, method: :patch, class: "button-xs btn-warning" %>
```suggestion
              <%= link_to t("action.unsuspend"), unsuspend_user_path(user), data: { confirm: t("action.confirm") }, method: :patch, class: "button-xs btn-succes" %>
```

2024-03-27 15:20 UTC, B-Rass commented on app/views/users/index.html.erb
> +              <%= link_to t("action.unsuspend"), unsuspend_user_path(user), data: { confirm: t("action.confirm") }, method: :patch, class: "button-xs btn-warning" %>
Better in green now ? or blue at least, but not the same color I think

2024-03-27 16:16 UTC, nicolas-brousse commented on spec/requests/users_request_spec.rb
Could I work on this in a separate pull request?

2024-03-27 16:16 UTC, nicolas-brousse commented on app/views/users/index.html.erb
> +              <%= link_to t("action.unsuspend"), unsuspend_user_path(user), data: { confirm: t("action.confirm") }, method: :patch, class: "button-xs btn-warning" %>
Ok for blue. I'll change it.

2024-03-27 16:43 UTC, nicolas-brousse commented on app/views/users/index.html.erb
> +              <%= link_to t("action.unsuspend"), unsuspend_user_path(user), data: { confirm: t("action.confirm") }, method: :patch, class: "button-xs btn-warning" %>
Changed

2024-03-27 16:43 UTC, nicolas-brousse commented on config/locales/fr.yml
> +      can_be_updated: Une erreur est survenue pendant la mise à jour
Fixed

2024-03-27 16:43 UTC, nicolas-brousse commented on app/controllers/users_controller.rb
> +      redirect_to users_path, alert: t(".flashes.can_be_updated")
Fixed

2024-03-29 15:19 UTC, B-Rass commented on spec/requests/users_request_spec.rb
Ok, here is the issue : https://github.com/nanego/my-dcim/issues/165

2024-03-29 15:20 UTC, B-Rass approved these changes

2024-03-29 15:20 UTC, merged