Add suspend scope to users
nanego/my-dcim pull request #174
Opened 2024-04-10 15:22 UTC by MBausson

Also adds a filter on users#index to filter by suspend/not suspended

2024-04-10 15:24 UTC, MBausson commented
I'm not sure of the bootstrap component used to make the filter for suspended / unsuspended on users#index

2024-04-11 08:28 UTC, nicolas-brousse requested changes
@MBausson Some small changes, otherwise LGTM

2024-04-11 08:28 UTC, nicolas-brousse commented on app/controllers/users_controller.rb
> +    if params[:suspended]&.casecmp('true')&.zero?
```suggestion
    if params[:suspended].present?
```

This may be enough

2024-04-11 08:28 UTC, nicolas-brousse commented on config/locales/fr.yml
> +      unsuspended: Non suspendus
```suggestion
      unsuspended: Actifs
```

2024-04-11 08:28 UTC, nicolas-brousse commented on config/locales/fr.yml
> +      suspended: Suspendus
```suggestion
      suspended: Vérouillés
```

2024-04-17 12:23 UTC, nicolas-brousse approved these changes

2024-04-17 12:24 UTC, merged