320594 Store user settings
nanego/my-dcim pull request #181
Opened 2024-05-02 12:01 UTC by MBausson

2024-05-02 16:11 UTC, nicolas-brousse commented on db/migrate/20240502093805_enable_hstore.rb
Is this pg extension necessary?

2024-05-02 16:11 UTC, nicolas-brousse commented on app/views/users/settings/edit.html.erb
> +  <%= form_for @user, url: users_settings_path do |f| %>
```suggestion
  <%= form_with model: @user, url: users_settings_path do |f| %>
```

2024-05-02 16:11 UTC, nicolas-brousse commented on app/views/users/settings/edit.html.erb
> +      <%= f.select :locale, User::AVAILABLE_LOCALES.compact, selected: @user.locale, class: "form-control" %>
`selected` should not be necessary if form configured properly

2024-05-02 16:11 UTC, nicolas-brousse commented on app/views/users/settings/edit.html.erb
> +      <%#= f.select :theme, User::AVAILABLE_THEMES.compact, selected: @user.theme, class: "form-control" %>
`selected` should not be necessary if form configured properly

2024-05-02 16:11 UTC, nicolas-brousse commented on app/views/users/settings/edit.html.erb
> +                   selected: @user.visualization_bay_default_background_color, class: "form-control" %>
`selected` should not be necessary if form configured properly

2024-05-02 16:11 UTC, nicolas-brousse commented on app/views/users/settings/edit.html.erb
> +                   selected: @user.visualization_bay_default_orientation, class: "form-control" %>
`selected` should not be necessary if form configured properly

2024-05-02 16:11 UTC, nicolas-brousse commented on app/views/users/settings/edit.html.erb
> +      <%= f.select :locale, User::AVAILABLE_LOCALES.compact, selected: @user.locale, class: "form-control" %>
What's `compact` used for?

2024-05-02 16:11 UTC, nicolas-brousse commented on app/models/user.rb
> +  AVAILABLE_LOCALES = (I18n.available_locales.map(&:to_s) << nil).freeze
```suggestion
  AVAILABLE_LOCALES = I18n.available_locales.map(&:to_s).freeze
```

No needs of `nil`. You have to use `allow_nil: true` in validator (apply the same on every validators related to settings

2024-05-03 08:47 UTC, MBausson commented on db/migrate/20240502093805_enable_hstore.rb
No, i removed this migration

2024-05-03 09:03 UTC, MBausson commented on app/views/users/settings/edit.html.erb
> +      <%= f.select :locale, User::AVAILABLE_LOCALES.compact, selected: @user.locale, class: "form-control" %>
Since every constants had a nil value, I wanted not to show it on views
The `compact` is not necessary anymore

2024-05-03 09:06 UTC, MBausson commented on app/views/users/settings/edit.html.erb
> +      <%= f.select :locale, User::AVAILABLE_LOCALES, class: "form-control" %>
@nicolas-brousse Do you have an idea of why the class is not being applied on the select ?

2024-05-17 09:46 UTC, B-Rass approved these changes

2024-05-17 09:49 UTC, B-Rass commented
@nicolas-brousse I don't know if we merge this, because if an user choose `english` as his locale, then the site will crash, and will not be able to update it. 


+ I let you review my small changes

2024-05-29 08:41 UTC, nicolas-brousse requested changes
@MBausson here is my review.

2024-05-29 08:41 UTC, nicolas-brousse commented on app/controllers/concerns/localization.rb
> +      I18n.locale = current_user&.locale || I18n.default_locale.to_s
Does `to_s` necessary?

2024-05-29 08:41 UTC, nicolas-brousse commented on config/locales/en.yml
Add missing translations

2024-05-29 08:41 UTC, nicolas-brousse commented on config/locales/activerecord.fr.yml
Add this tranlations in `en` file

2024-05-29 08:41 UTC, nicolas-brousse commented on app/views/rooms/show.html.erb
> +                              <% bgModeleColor = define_background_color(server: server, mode: bg || Modele.model_name.human.downcase) %>
For which usage `Modele.model_name.human.downcase` has been added?

2024-05-29 08:41 UTC, nicolas-brousse commented on app/views/rooms/show.html.erb
> +<% view = params[:view].presence || current_user.visualization_bay_default_orientation == 'rear' ? 'back' : 'front' %>
Is there any reason for using `rear` in our settings instead `back`?

2024-05-29 08:41 UTC, nicolas-brousse commented on app/views/rooms/show.html.erb
> +            <%= t("rooms.action_buttons.background_color", bg: bg || Modele.model_name.human.downcase) %> <span class="caret"></span>
Not sure about using `Modele.model_name.human.downcase`. It seams to be a key here, so if we rename Modele model name translation, this will break this code.

2024-05-29 08:41 UTC, nicolas-brousse commented on app/views/rooms/show.html.erb
> +
Is this still necessary? `searchParams` seams not to be used anymore

2024-05-29 08:41 UTC, nicolas-brousse commented on app/views/users/settings/edit.html.erb
> +                   User::AVAILABLE_LOCALES.map { |locale| [User.human_attribute_name("locale.#{locale}"), locale] },
Move this in a decorator.

For example:
```rb
class << self
    def available_locales_for_options
      AVAILABLE_LOCALES.map { |locale| [User.human_attribute_name("locale.#{locale}"), locale] }
    end
end
```

2024-05-29 08:41 UTC, nicolas-brousse commented on app/views/users/settings/edit.html.erb
> +                   User::AVAILABLE_LOCALES.map { |locale| [User.human_attribute_name("locale.#{locale}"), locale] },
Also do the same for the others select

2024-05-29 12:32 UTC, MBausson commented on app/views/rooms/show.html.erb
> +<% view = params[:view].presence || current_user.visualization_bay_default_orientation == 'rear' ? 'back' : 'front' %>
No, I actually used the same values as in the issue

2024-05-29 15:36 UTC, nicolas-brousse requested changes
@MBausson 2 last changes otherwise LGTM

2024-05-29 15:36 UTC, nicolas-brousse commented on app/views/users/settings/edit.html.erb
> +      <%#= f.select :theme, User::AVAILABLE_THEMES.compact, class: "form-control" %>
Move this in the decorator too.

2024-05-29 15:36 UTC, nicolas-brousse commented on app/decorators/user_decorator.rb
Add decorator tests

2024-05-29 15:39 UTC, nicolas-brousse requested changes

2024-05-29 15:39 UTC, nicolas-brousse commented on app/views/users/settings/edit.html.erb
> +      <%= f.select :locale, UserDecorator::available_background_colors_for_options, {}, class: "form-control" %>
Not the good options.

2024-05-30 08:54 UTC, nicolas-brousse approved these changes

2024-05-30 08:55 UTC, merged