Add feature test ror RoomsController#show
nanego/my-dcim pull request #196
Opened 2024-07-01 15:59 UTC by MBausson

2024-07-03 09:22 UTC, MBausson commented on test/controllers/frames_controller_test.rb
> +      post :create, params: { frame: { name: "MyFrame4", bay_id: 1 } }
Since I added slugs to frames fixtures, the test failed because of a unique constraint violation on slugs

2024-07-24 15:20 UTC, B-Rass requested changes

2024-07-24 15:20 UTC, B-Rass commented on Gemfile
> +  gem "formulaic"
Can you put this line where it belongs, after `cuprite` line

2024-07-29 12:41 UTC, nicolas-brousse commented on spec/features/rooms/browse_room_spec.rb
> +    sleep 1
What this for?

2024-07-29 14:52 UTC, MBausson commented on spec/features/rooms/browse_room_spec.rb
> +    sleep 1
Since the view is loaded via javascript, we cannot use `find()` to wait for the DOM to be updated because this is already done earlier in the test

2024-08-01 08:37 UTC, B-Rass approved these changes

2024-08-07 14:49 UTC, nicolas-brousse approved these changes

2024-08-07 14:51 UTC, merged