341626 - Move Rooms, Frames and Bays #show in a new namespaced controller
nanego/my-dcim pull request #205
Opened 2024-09-10 14:18 UTC by MBausson

2024-09-11 08:49 UTC, nicolas-brousse commented on app/controllers/visualization/bays_controller.rb
> +    end
@nicolas-brousse verify this is not used in other actions

2024-09-18 13:06 UTC, nicolas-brousse requested changes
Move Bays, Frames, Rooms #print actions in Visualization controllers. And clean others controllers from unused code (mainly before_actions)

2024-09-18 15:45 UTC, MBausson commented on app/views/rooms/_action_buttons.html.erb
> +          <%= link_to print_frame_path(params.except(:controller, :action, :id).permit(:view, :islet, :bg)),
```undefined method `take' for an instance of ActionController::Parameters```

2024-09-25 16:03 UTC, nicolas-brousse approved these changes

2024-09-25 16:04 UTC, merged