341617 - Add ChangelogEntry to show pages
nanego/my-dcim pull request #210
Opened 2024-09-11 15:47 UTC by MBausson

2024-09-12 08:27 UTC, MBausson commented on app/helpers/changelog_entries_helper.rb
> +    tag.turbo_frame(id: "changelog-entries", loading: :lazy, src: object_changelog_entries_path(object), **)
Would it be interesting to add a sort of "loading" content to show while loading the turbo frame ?

2024-09-12 09:24 UTC, nicolas-brousse requested changes

2024-09-12 09:24 UTC, nicolas-brousse commented on app/helpers/changelog_entries_helper.rb
> +    tag.turbo_frame(id: "changelog-entries", loading: :lazy, src: object_changelog_entries_path(object), **)
Yes. Also it may be better to use decorator instead helper

2024-09-12 09:24 UTC, nicolas-brousse commented on app/helpers/changelog_entries_helper.rb
> +    "/#{object.class.name.underscore.pluralize}/#{object.id}/changelog_entries"
We should found a better way

2024-09-12 09:24 UTC, nicolas-brousse commented on app/helpers/changelog_entries_helper.rb
> +    tag.turbo_frame(id: "changelog-entries", loading: :lazy, src: object_changelog_entries_path(object), **)
Use turbo frame helper https://github.com/hotwired/turbo-rails/blob/main/app/helpers/turbo/frames_helper.rb

2024-09-12 09:24 UTC, nicolas-brousse commented on app/views/changelog_entries/index.html.erb
> +<turbo-frame id="changelog-entries">
Use turbo frame helper https://github.com/hotwired/turbo-rails/blob/main/app/helpers/turbo/frames_helper.rb

2024-09-18 12:22 UTC, nicolas-brousse requested changes

2024-09-18 15:37 UTC, nicolas-brousse commented
@B-Rass if it's good for you, then it may be apply on every pages.

2024-10-02 10:03 UTC, nicolas-brousse approved these changes

2024-10-02 15:51 UTC, B-Rass approved these changes

2024-10-02 15:53 UTC, merged