343808 - Add presence and format validation on Card name
nanego/my-dcim pull request #234
Opened 2024-10-16 13:20 UTC by nicolas-brousse

2024-11-06 16:31 UTC, B-Rass commented on spec/models/composant_spec.rb
>      xit { is_expected.to be_valid }
Did you look why this test is deactivated?

2024-11-06 16:36 UTC, B-Rass requested changes
Maybe we should make it more explicit. Or make the field form red? Or both?

2024-11-06 16:51 UTC, nicolas-brousse commented on spec/models/composant_spec.rb
>      xit { is_expected.to be_valid }
The object need to have associations set correctly for that

2024-11-06 16:52 UTC, nicolas-brousse commented
> Maybe we should make it more explicit. Or make the field form red? Or both?

I improved the error message

2024-11-07 09:54 UTC, B-Rass approved these changes

2024-11-07 10:00 UTC, merged