341629 Add new attributes (width/depth/manufacturer) to Bay
nanego/my-dcim pull request #244
Opened 2024-10-29 17:44 UTC by B-Rass

2024-11-13 10:36 UTC, nicolas-brousse requested changes

2024-11-13 10:36 UTC, nicolas-brousse commented on app/views/manufacturers/index.html.erb
> +      <%= Manufacturer.human_attribute_name(:bays_count, count: manufacturer.bays_count) %>
Maybe we could add like to filtered bays list view

2024-11-13 10:36 UTC, nicolas-brousse commented on app/views/manufacturers/index.html.erb
>        <%= Manufacturer.human_attribute_name(:modeles_count, count: manufacturer.modeles_count) %>
Maybe we could add like to filtered modeles list view

2024-11-13 10:36 UTC, nicolas-brousse commented on app/views/bays/show.html.erb
> +          <dd class="mb-0 pb-2 ps-3"><%= value_with_unit(@bay.depth, "mm") if @bay.depth.present? %></dd>
What about updating `value_with_unit` to not print the unit when value is blank?

2024-11-13 10:36 UTC, nicolas-brousse commented on app/processors/bays_processor.rb
> +
Seems test to be missing

2024-11-15 10:51 UTC, nicolas-brousse reviewed
@B-Rass one last question

2024-11-15 10:51 UTC, nicolas-brousse commented on app/views/manufacturers/index.html.erb
> +      <% end %>
May we add the filter in filter form in sites too?

2024-11-15 10:57 UTC, B-Rass commented on app/views/manufacturers/index.html.erb
> +      <% end %>
Yes you're right, done

2024-11-15 11:41 UTC, merged