Add warning icon on bay if it has no frame associated
nanego/my-dcim pull request #256
Opened 2024-11-07 18:02 UTC by B-Rass

2024-11-13 10:05 UTC, nicolas-brousse requested changes

2024-11-13 10:05 UTC, nicolas-brousse commented on app/components/page/heading_component.rb
> +            <h1 class="text-center"><%= @title.to_s.html_safe %></h1>
Prefer to apply `html_safe` in the `show.html.erb` view. That way we apply it really when we want to. It's a bit more secure.

```erb
<%= render Page::HeadingShowComponent.new(resource: @bay, title: title.html_safe, breadcrumb_steps:) do |heading| %>
   ...
<% end %>
```

2024-11-13 10:05 UTC, nicolas-brousse commented on app/views/bays/index.html.erb
> +        <%= link_to link_text, bay_path(bay), data: { turbo_frame: :_top } %>
**Optional**. We may move the text in a block with condition.

2024-11-13 10:54 UTC, B-Rass commented on app/views/bays/index.html.erb
> +        <%= link_to link_text, bay_path(bay), data: { turbo_frame: :_top } %>
I don't get it

2024-11-15 11:00 UTC, nicolas-brousse approved these changes

2024-11-15 11:05 UTC, merged