343816 add button to delete connection on server show
nanego/my-dcim pull request #275
Opened 2024-11-27 15:14 UTC by B-Rass

2024-11-28 17:26 UTC, B-Rass commented on config/locales/fr.yml
> +        connections_destroyed: Les connexions ont été supprimées
```suggestion
        connections_destroyed: Les connexions ont été supprimées.
```

2024-11-28 17:26 UTC, B-Rass commented on config/locales/fr.yml
> +        connections_not_destroyed: Une erreur a empêché la suppression des connexions
```suggestion
        connections_not_destroyed: Une erreur a empêché la suppression des connexions.
```

2024-12-04 14:07 UTC, nicolas-brousse requested changes

2024-12-04 14:38 UTC, B-Rass commented on spec/requests/servers_request_spec.rb
> +  end
Sure, but I can't find a case when it will fail

2024-12-04 16:36 UTC, nicolas-brousse approved these changes

2024-12-04 16:36 UTC, nicolas-brousse commented on spec/requests/servers_request_spec.rb
> +  end
I don't have any case in head. So let keep this like it is

2024-12-04 16:36 UTC, merged