Update dependencies
nanego/my-dcim pull request #302
Opened 2024-12-11 16:15 UTC by nicolas-brousse

2024-12-11 16:26 UTC, B-Rass requested changes

2024-12-11 16:26 UTC, B-Rass commented on app/models/processor_filter.rb
> +    @rubanok_class = with || guess_processor_from_records
```suggestion
    @rubanok_class = with || guess_processor_from_records(@records)
```

2024-12-11 16:35 UTC, B-Rass commented
I can't build. I have an error with `mini-racer`.

```
Installing mini_racer 0.15.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/mini_racer-0.15.0/ext/mini_racer_extension
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/bin/ruby extconf.rb
checking for -lpthread... yes
checking for -lobjc... yes


WARNING: C++11 support is required for compiling mini_racer. Please make sure
you are using a compiler that supports at least C++11. Examples of such
compilers are GCC 4.7+ and Clang 3.2+.

If you are using Travis, consider either migrating your build to Ubuntu Trusty or
installing GCC 4.8. See mini_racer's README.md for more information.


checking for whether -Wl,--exclude-libs=ALL  is accepted as LDFLAGS... no
creating Makefile

current directory: /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/mini_racer-0.15.0/ext/mini_racer_extension
make DESTDIR\= sitearchdir\=./.gem.20241211-61016-mowe27 sitelibdir\=./.gem.20241211-61016-mowe27 clean

current directory: /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/mini_racer-0.15.0/ext/mini_racer_extension
make DESTDIR\= sitearchdir\=./.gem.20241211-61016-mowe27 sitelibdir\=./.gem.20241211-61016-mowe27
compiling mini_racer_extension.cc
make: *** [mini_racer_extension.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/mini_racer-0.15.0 for inspection.
Results logged to /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/extensions/arm64-darwin-24/3.3.0/mini_racer-0.15.0/gem_make.out

  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:51:in `block in make'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `each'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `make'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/installer.rb:844:in `build_extensions'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/rubygems_gem_installer.rb:76:in `build_extensions'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/source/rubygems.rb:205:in `install'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/installer/parallel_installer.rb:132:in `do_install'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/worker.rb:62:in `apply_func'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/worker.rb:57:in `block in process_queue'
  <internal:kernel>:187:in `loop'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/worker.rb:54:in `process_queue'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing mini_racer (0.15.0), and Bundler cannot continue.
```

2024-12-18 15:53 UTC, nicolas-brousse commented
@B-Rass fixed

2024-12-18 16:02 UTC, B-Rass commented
> @B-Rass fixed

I still have an error on `mini-racer`

```
Installing mini_racer 0.15.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/mini_racer-0.15.0/ext/mini_racer_extension
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/bin/ruby extconf.rb
checking for -lpthread... yes
checking for -lobjc... yes


WARNING: C++11 support is required for compiling mini_racer. Please make sure
you are using a compiler that supports at least C++11. Examples of such
compilers are GCC 4.7+ and Clang 3.2+.

If you are using Travis, consider either migrating your build to Ubuntu Trusty or
installing GCC 4.8. See mini_racer's README.md for more information.


checking for whether -Wl,--exclude-libs=ALL  is accepted as LDFLAGS... no
creating Makefile

current directory:
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/mini_racer-0.15.0/ext/mini_racer_extension
make DESTDIR\= sitearchdir\=./.gem.20241218-97072-1fh97o sitelibdir\=./.gem.20241218-97072-1fh97o clean

current directory:
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/mini_racer-0.15.0/ext/mini_racer_extension
make DESTDIR\= sitearchdir\=./.gem.20241218-97072-1fh97o sitelibdir\=./.gem.20241218-97072-1fh97o
compiling mini_racer_extension.cc
make: *** [mini_racer_extension.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/mini_racer-0.15.0 for inspection.
Results logged to
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/extensions/arm64-darwin-24/3.3.0/mini_racer-0.15.0/gem_make.out

  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:51:in `block in make'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `each'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `make'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in
build_extensions'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/rubygems/installer.rb:844:in `build_extensions'
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/rubygems_gem_installer.rb:76:in
`build_extensions'
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/source/rubygems.rb:205:in
`install'
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/installer/gem_installer.rb:54:in
`install'
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/installer/parallel_installer.rb:132:in
`do_install'
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/installer/parallel_installer.rb:123:in
`block in worker_pool'
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/worker.rb:62:in
`apply_func'
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/worker.rb:57:in
`block in process_queue'
  <internal:kernel>:187:in `loop'
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/worker.rb:54:in
`process_queue'
/Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/lib/bundler/worker.rb:90:in
`block (2 levels) in create_threads'

An error occurred while installing mini_racer (0.15.0), and Bundler cannot continue.

In Gemfile:
  mini_racer
bin/setup:8:in `system': Command failed with exit 5: bundle (RuntimeError)
	from bin/setup:8:in `system!'
	from bin/setup:18:in `block in <main>'
	from /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/fileutils.rb:240:in `chdir'
	from /Users/b.rasschaert/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/fileutils.rb:240:in `cd'
	from bin/setup:11:in `<main>'
```

2024-12-18 16:04 UTC, nicolas-brousse commented
I previously got the error too, but not anymore in my side...

2024-12-18 16:11 UTC, B-Rass requested changes
The `mini-racer` error

2025-01-29 14:02 UTC, B-Rass approved these changes

2025-01-29 14:02 UTC, merged