127609 - Empecher la suppresion d'un type de carte s'il est utilisé
nanego/my-dcim pull request #46
Opened 2023-01-18 15:21 UTC by francoisedumas

[User story](https://app.activecollab.com/170818/projects/278/tasks/3344)

2023-01-18 16:55 UTC, nicolas-brousse commented on .byebug_history
> +Site.count
Add this file in `.gitignore` file

2023-01-18 17:00 UTC, francoisedumas commented on .byebug_history
> +Site.count
Done

2023-02-08 17:37 UTC, nicolas-brousse requested changes
@B-Rass may you add some tests for `ArchitecturesController`, `CardTypesController`, `ClustersController`, `DiskTypesController`, `DomainsController`, `IsletsController`, `MaintainersController`, `ManufacturersController`,  `MemoryTypesController`, `RoomsController` and `StacksController` like we did for the others?

2023-02-15 15:15 UTC, nicolas-brousse approved these changes

2023-02-15 15:15 UTC, merged