275817 - Use i18n on Site resource
nanego/my-dcim pull request #77
Opened 2023-10-04 12:02 UTC by MBausson

2023-10-04 13:13 UTC, nicolas-brousse requested changes
@MBausson let me know if some messages are not clear enough

2023-10-04 13:13 UTC, nicolas-brousse commented on app/views/pages/_params_menu.html.erb
> +    <a href="<%= servers_path %>" class="list-group-item <%= controller.controller_name == "servers" ? 'active' : '' %>"><%= t(".material.materials") %></a>
To be changed like items in localisation

2023-10-04 13:13 UTC, nicolas-brousse commented on app/views/pages/_params_menu.html.erb
> +    <a href="<%= memory_types_path %>" class="list-group-item <%= controller.controller_name == "memory_types" ? 'active' : '' %>"><%= t(".material_management.memory_types") %></a>
To be changed like items in localisation

2023-10-04 13:13 UTC, nicolas-brousse commented on app/views/sites/_form.html.erb
> +      <%= f.submit t(".submit"), class: "btn btn-primary" %>
```suggestion
      <%= f.submit t(".form.submit"), class: "btn btn-primary" %>
```

2023-10-04 13:13 UTC, nicolas-brousse commented on app/views/sites/edit.html.erb
> +    <%= t("page_action.back") %>
```suggestion
    <%= t("action.back") %>
```

2023-10-04 13:13 UTC, nicolas-brousse commented on app/controllers/sites_controller.rb
> +        format.html { redirect_to sites_path, notice: t(".notice") }
```suggestion
        format.html { redirect_to sites_path, notice: t(".flashes.created") }
```

@B-Rass what do you think about? Any other suggestion?

2023-10-04 13:13 UTC, nicolas-brousse commented on app/views/sites/show.html.erb
>    <dd><%= @site.longitude %></dd>
I suggest to loop on attributes names here

```rb
<% %i[name position ...].each do |attribute_name| %>
  <dt><%= Site.human_attribute_name(attribute_name) %> :</dt>
  <dd><%= @site.public_send(attribute_name) %>
<% end %>
```

@B-Rass over-killed? or interesting?

2023-10-04 13:13 UTC, nicolas-brousse commented on app/views/sites/index.html.erb
> +        accessToken: ''
@MBausson mistake here

2023-10-04 13:13 UTC, nicolas-brousse commented on app/views/sites/_form.html.erb
> +      <h4><%= Site.human_attribute_name(:errors_count, count: @site.errors.count) %> <%= t(".error_title") %></h4>
```suggestion
      <h4><%= t("form.errors.title", object_name: Site.human_attribute_name(:errors_count, count: @site.errors.count) %></h4>
```

Make object name part of error title.

2023-10-04 13:27 UTC, B-Rass commented on app/views/sites/show.html.erb
>    <dd><%= @site.longitude %></dd>
Okay, good idea

2023-10-04 13:27 UTC, B-Rass commented on app/controllers/sites_controller.rb
> +        format.html { redirect_to sites_path, notice: t(".notice") }
Whad do I think about what ?

2023-10-04 13:46 UTC, MBausson commented on app/views/pages/_params_menu.html.erb
> +    <a href="<%= servers_path %>" class="list-group-item <%= controller.controller_name == "servers" ? 'active' : '' %>"><%= t(".material.materials") %></a>
@nicolas-brousse  I can't find out from which model Matériel is taken from, in order to apply .model_name

2023-10-04 13:49 UTC, nicolas-brousse commented on app/controllers/sites_controller.rb
> +        format.html { redirect_to sites_path, notice: t(".notice") }
my code suggestion, to be more precise on flash message key in controllers. Maybe there is a better key syntax

2023-10-04 13:51 UTC, nicolas-brousse commented on app/views/pages/_params_menu.html.erb
> +    <a href="<%= servers_path %>" class="list-group-item <%= controller.controller_name == "servers" ? 'active' : '' %>"><%= t(".material.materials") %></a>
Keep it untranslated for now then. It's kind of specific for this one.

2023-10-04 13:53 UTC, B-Rass commented on app/controllers/sites_controller.rb
> +        format.html { redirect_to sites_path, notice: t(".notice") }
I can't find a situation where more precision can be a bad decision here

2023-10-04 14:43 UTC, B-Rass commented on app/controllers/sites_controller.rb
> +        format.html { redirect_to sites_path, notice: t(".notice") }
sure

2023-10-04 15:21 UTC, nicolas-brousse requested changes
@MBausson some new feedback

2023-10-04 15:21 UTC, nicolas-brousse commented on app/views/sites/_form.html.erb
> +      <h4><%= t('form.errors.title', object_name: Site.human_attribute_name(:errors_count, count: @site.errors.count)) %> </h4>
Sorry I did check enough the original code before reviewing.

```suggestion
      <h4><%= t('form.errors.title', count: @site.errors.count) %> </h4>
```

This should be enough, and then manage count in locale file

2023-10-04 15:21 UTC, nicolas-brousse commented on app/views/sites/index.html.erb
> +        integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX6ë8nAhlwcDFLGPCQ=="
@MBausson I think you did a typo here

2023-10-04 15:32 UTC, MBausson commented on app/views/sites/_form.html.erb
> +      <h4><%= t('form.errors.title', object_name: Site.human_attribute_name(:errors_count, count: @site.errors.count)) %> </h4>
@nicolas-brousse How should this handle plurality ?

2023-10-04 15:45 UTC, nicolas-brousse requested changes
@MBausson just one last change for me, otherwise LGTM

2023-10-04 15:45 UTC, nicolas-brousse commented on config/locales/fr.yml
> +      #contract_type: Type de contrat
Remove it

2023-10-04 15:46 UTC, nicolas-brousse commented on app/views/sites/_form.html.erb
> +      <h4><%= t('form.errors.title', object_name: Site.human_attribute_name(:errors_count, count: @site.errors.count)) %> </h4>
@MBausson with `one:`  and `other:` like you did for some other keys.

2023-10-04 15:57 UTC, B-Rass requested changes
@MBausson On the views you worked on, can you replace string with simple quotes, by double quotes ?

Thanks !

Otherwhile ready to be merged for me !

2023-10-04 15:57 UTC, B-Rass commented on app/views/pages/_params_menu.html.erb
> +    <a href="<%= modeles_path %>" class="list-group-item <%= controller.controller_name == "modeles" ? 'active' : '' %>"><%= Modele.model_name.human.pluralize %></a>
```suggestion
    <a href="<%= modeles_path %>" class="list-group-item <%= controller.controller_name == "modeles" ? "active" : "" %>"><%= Modele.model_name.human.pluralize %></a>
```

@MBausson I like stuff to be consistent ^^

So it could be nice to profit of this issue, to normalize string on this file and user double-quote instead simple-quote on this file

2023-10-04 15:57 UTC, B-Rass commented on app/views/sites/_form.html.erb
> +      <h4><%= t('form.errors.title', count: @site.errors.count) %> </h4>
```suggestion
      <h4><%= t("form.errors.title", count: @site.errors.count) %> </h4>
```

2023-10-04 15:57 UTC, B-Rass commented on app/views/sites/index.html.erb
> +<%= render 'layouts/breadcrumb', breadcrumb_variables: {
```suggestion
<%= render "layouts/breadcrumb", breadcrumb_variables: {
```

2023-10-04 15:57 UTC, B-Rass commented on app/views/sites/index.html.erb
> +  Site.model_name.human.pluralize => '' }
```suggestion
  Site.model_name.human.pluralize => "" }
```

2023-10-11 08:32 UTC, nicolas-brousse requested changes

2023-10-11 08:32 UTC, nicolas-brousse commented on config/locales/fr.yml
> +        bays: Baies / Doubles-baies
@MBausson this key seems to not being used anymore

2023-10-11 08:32 UTC, nicolas-brousse commented on config/locales/fr.yml
> +          position: Position
@MBausson theses keys seems to net being used anymore

2023-10-11 08:32 UTC, nicolas-brousse commented on app/views/sites/index.html.erb
> +                          data: { confirm: t(".table.body.delete.confirmation") },
```suggestion
                          data: { confirm: t(".delete_confirmation") },
```

I let you update the locale file too.

2023-10-11 09:19 UTC, MBausson commented on config/locales/fr.yml
> +        bays: Baies / Doubles-baies
pages.params_menu.location.bays is used in pages/_params_menu.html.erb:10

2023-10-11 11:47 UTC, nicolas-brousse approved these changes

2023-10-11 11:49 UTC, merged