275817 - Use i18n islet resource
nanego/my-dcim pull request #79
Opened 2023-10-06 10:17 UTC by MBausson

2023-10-11 09:12 UTC, nicolas-brousse requested changes
@MBausson I've to check a bit more, but here is my first review

2023-10-11 15:12 UTC, nicolas-brousse commented on config/locales/activerecord.fr.yml
> +          other: '%{count} erreurs'
@MBausson seems not to be used anymore?

2023-10-11 15:13 UTC, nicolas-brousse commented on config/locales/activerecord.fr.yml
> +        room: Salle
@MBausson Not sure it's still used

2023-10-31 10:04 UTC, MBausson commented on config/locales/activerecord.fr.yml
> +        room: Salle
They are used in the Islet form partial, for the labels

2023-11-10 13:37 UTC, B-Rass approved these changes
Good!

2023-11-22 16:33 UTC, nicolas-brousse commented on config/locales/fr.yml
> +    port_list: Liste des ports
@B-Rass wdya

```yml
export_button:
  label: Exports
  pdf:
    label: Export pdf
    front_face: Face avant
    back_face: Face arrière
    wires_front_face: Cablage - Face avant
    wires_back_face: Cablage - Face arrière
  txt:
    label: Export Txt
  print:
    label: Impression
  ports_list: Liste des ports
```

2023-11-22 17:19 UTC, B-Rass commented on config/locales/fr.yml
> +    port_list: Liste des ports
yes good

2023-12-06 14:44 UTC, nicolas-brousse requested changes
@MBausson one last change otherwise LGTM

2023-12-06 15:30 UTC, MBausson commented on app/views/islets/index.html.erb
> +              <%= Frame.model_name.human %>
Je n'ai pas mit le .pluralize, car le nom du model est traduit en "Châsses" au lieu de "Châssis" au pluriel

2023-12-06 16:54 UTC, nicolas-brousse commented on app/views/islets/index.html.erb
> +              <%= Frame.model_name.human %>
Met à jour `config/initializers/inflections.rb`

Avec cette méthode https://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html#method-i-uncountable.

2023-12-13 15:42 UTC, merged