275817 - Use i18n bay resource
nanego/my-dcim pull request #80
Opened 2023-10-06 10:18 UTC by MBausson

2023-10-11 09:12 UTC, nicolas-brousse requested changes
@MBausson I've to check a bit more, but here is my first review

2023-10-11 09:12 UTC, nicolas-brousse commented on app/views/rooms/_action_buttons.html.erb
> +      <%= (view_side==Frame.view_sides[:back] ? t(".views.front") : t(".views.back")) %>
@MBausson Use Record attribute translation here. See this section on documentation https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models (refer to roles example)

2023-10-11 09:12 UTC, nicolas-brousse commented on app/views/bays/new.html.erb
> +%>
```suggestion
<%= render "layouts/breadcrumb", breadcrumb_variables: {
  t("breadcrumb.settings") => modeles_url,
  t("breadcrumb.bays.index") => bays_path,
  t("breadcrumb.bays.new") => ""}
%>
```

2023-11-29 09:59 UTC, B-Rass requested changes

2023-11-29 09:59 UTC, B-Rass commented on config/locales/fr.yml
> +        destroyed: La bay bien été supprimé.
```suggestion
        destroyed: La baie bien été supprimé.
```

2023-11-29 09:59 UTC, B-Rass commented on config/locales/fr.yml
> +        cluster: Cluster
@nicolas-brousse Pourquoi ne pas directement utiliser les noms des modèles ici ?

2024-01-31 13:35 UTC, B-Rass requested changes

2024-01-31 13:35 UTC, B-Rass commented on config/locales/activerecord.fr.yml
> +          zero: 0 serveurs
```suggestion
          zero: 0 serveur
```

2024-01-31 13:44 UTC, nicolas-brousse approved these changes

2024-01-31 15:54 UTC, B-Rass approved these changes

2024-01-31 15:54 UTC, merged