275817 - Use i18n for frame resource
nanego/my-dcim pull request #81
Opened 2023-10-06 14:48 UTC by MBausson

2023-10-11 16:53 UTC, B-Rass requested changes
Some miss to add

@nicolas-brousse need your opinion on one comment

2023-10-11 16:53 UTC, B-Rass commented on app/views/servers/_modal_add_element_in_frame.html.erb
>                <%= f.submit 'Confirmer',class: "btn btn-primary" %>
Missing Translation on `Confirmer`

2023-12-06 15:26 UTC, nicolas-brousse requested changes

2023-12-06 15:26 UTC, nicolas-brousse commented on config/locales/activerecord.fr.yml
> +        room: Salle
@MBausson still used?

2023-12-06 15:48 UTC, MBausson commented on config/locales/activerecord.fr.yml
> +        room: Salle
Yes, in the frames index file, for the <th>

2024-01-10 15:37 UTC, B-Rass approved these changes

2024-01-24 15:26 UTC, nicolas-brousse approved these changes

2024-01-24 15:36 UTC, B-Rass requested changes
1 question and good to merge @nicolas-brousse

2024-01-24 15:36 UTC, B-Rass commented on app/models/server.rb
> -      errors.add(:numero, "ne peut pas être identique à un nom de machine")
Autant le faire maintenant nan ?

2024-01-24 15:47 UTC, nicolas-brousse commented on app/models/server.rb
> -      errors.add(:numero, "ne peut pas être identique à un nom de machine")
Done

2024-01-24 15:52 UTC, B-Rass approved these changes

2024-01-24 15:52 UTC, merged