275817 - i18n - manufacturer resource
nanego/my-dcim pull request #87
Opened 2023-10-11 15:34 UTC by MBausson

2023-10-11 16:26 UTC, B-Rass approved these changes
LGTM @nicolas-brousse

2023-10-11 16:41 UTC, B-Rass commented on app/views/manufacturers/index.html.erb
```rb
<%= render 'layouts/breadcrumb', breadcrumb_variables: {'Paramètres' => modeles_url, 'Fabricants' => ''} %>
```

2023-11-03 10:14 UTC, nicolas-brousse commented on app/views/manufacturers/_form.html.erb
> +        <small><%= t(".information").html_safe %></small>
`raw` call `html_safe` https://github.com/rails/rails/blob/23938052acd773fa24068debe56cd892cbf8d868/actionview/lib/action_view/helpers/output_safety_helper.rb#L18.

The idea is more to rename locale key with `_html` suffix.

2023-11-03 10:17 UTC, nicolas-brousse requested changes
@MBausson there is conflicts to resolve by doing a rebase from `master`. Also I add a comment about the local with html, it need to be changed.

2023-11-03 10:55 UTC, merged