275817 - i18n - domaine resource
nanego/my-dcim pull request #88
Opened 2023-10-11 15:59 UTC by MBausson

2023-10-11 16:43 UTC, B-Rass requested changes
One correction needed, otherwhile good to be merged

2023-10-18 15:34 UTC, nicolas-brousse requested changes
@MBausson some change to do

2023-10-18 15:34 UTC, nicolas-brousse commented on app/views/domaines/index.html.erb
> +  t("breadcrumb.settings") => modeles_url,
```suggestion
  t("breadcrumb.settings") => domaines_url,
```

2023-10-18 15:34 UTC, nicolas-brousse commented on config/locales/fr.yml
> +        updated: Domaine was successfully updated.
Translate in French

2023-10-18 15:34 UTC, nicolas-brousse commented on config/locales/fr.yml
> +        created: Domaine was successfully created.
Translate in French

2023-10-18 15:34 UTC, nicolas-brousse commented on config/locales/fr.yml
> +      title: New domaine
Translate in French

2023-11-02 15:41 UTC, nicolas-brousse requested changes

2023-11-02 15:41 UTC, nicolas-brousse commented on app/views/domaines/index.html.erb
> +  t("breadcrumb.domaines") => ""}
```suggestion
  Domaine.model_name.human.pluzalize => ""}
```

I let you clean the locale file too

2023-11-03 10:18 UTC, nicolas-brousse commented
@MBausson may you rebase from `master` and resolve conflicts? Otherwise LGTM

2023-11-03 10:59 UTC, merged